// "use client";

import type { Metadata } from "next";
import Link from "next/link";

type User = {
  id: number;
  name: string;
};

export const metadata: Metadata = {
  title: "Users",
  description: "Generated by create next app",
};

const Users = async () => {
  const res = await fetch("http://localhost:3000/api/users");
  const users = await res.json();

  return (
    <div className="h-screen bg-black text-neutral-200 flex justify-center items-center px-20">
      <div className="bg-white/5 flex flex-wrap justify-center items-center gap-5 border rounded-3xl border-neutral-600 h-[80vh] overflow-y-scroll no-scrollbar p-10 mt-20">
        {users?.map((user: User) => (
          <Link
            href={`/users/${user.id}`}
            key={user.id}
            className="w-[280px] h-[120px] relative hover:shadow-md shadow-blue-100 border-2 border-neutral-500 p-4 duration-300 cursor-pointer rounded-2xl flex gap-4 justify-center items-center"
          >
            <p className="text-xl">{user.id}</p>
            <h2 className="text-2xl font-bold">{user.name}</h2>
          </Link>
        ))}
      </div>
    </div>
  );
};

export default Users;
