export const products = [
    { id: 1, name: "Boat Headphones 123", category: "Electronics" },
    { id: 2, name: "Boat Earphones", category: "Electronics" },
    { id: 3, name: "Boat Mobile", category: "Electronics" },
    { id: 4, name: "Boat Refrigerator", category: "Electronics" },
    { id: 5, name: "HP Laptop", category: "Gadgets" },
    { id: 6, name: "HP Smartwatch", category: "Gadgets" },
    { id: 7, name: "HP Bluetooth Speaker", category: "Gadgets" },
    { id: 8, name: "HP Microwave Oven", category: "Gadgets" },
    { id: 9, name: "Sony Air Conditioner", category: "Electronics" },
    { id: 10, name: "Sony Smart TV", category: "Electronics" },
    { id: 11, name: "Sony Washing Machine", category: "Electronics" },
    { id: 12, name: "Sony Dishwasher", category: "Electronics" },
    { id: 13, name: "Sony Coffee Maker", category: "Electronics" },
    { id: 14, name: "Electric Kettle", category: "Electronics" },
    { id: 15, name: "Electric Toothbrush", category: "Electronics" },
    { id: 16, name: "Drone", category: "Electronics" },
    { id: 17, name: "Google Camera", category: "Electronics" },
    { id: 18, name: "Google Projector", category: "Vehicles" },
    { id: 19, name: "Apple Gaming Console", category: "Vehicles" },
    { id: 20, name: "Apple Virtual Reality Headset", category: "Vehicles" },
    { id: 21, name: "Apple Portable Charger", category: "Vehicles" },
    { id: 22, name: "Laptop Bag", category: "Accessories" },
    { id: 23, name: "Sony Phone Case", category: "Accessories" },
    { id: 24, name: "Keyboard", category: "Electronics" },
    { id: 25, name: "Sony Mouse", category: "Electronics" },
  ];