import Link from "next/link";
// import Navbar from "./Navbar";
import { addProduct } from "@/actions/FormActions";
import type { Metadata } from "next";

type Products = {
  id: number;
  name: string;
  category: string;
};

export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

// export async function generateStaticParams() {
//   return [{ id: "1" },{ id: "2" },{ id: "3" }];
// }

const Products = async () => {
  const res = await fetch("http://localhost:3000/api/products");
  const products = await res.json();


  return (
    <div className="min-h-screen bg-black text-white flex justify-center items-center">
      <div className="flex flex-col justify-center items-center w-full py-10 space-y-7 px-20">
        <div className="flex flex-col justify-center items-center space-y-3 mt-12">
          {/* <Navbar /> */}
          <form
            autoComplete="off"
            action={addProduct}
            className="flex flex-col gap-2 w-full justify-center items-center text-neutral-500"
          >
            <div className="flex gap-4">
              <div className="flex flex-col">
                <label htmlFor="name" className="text-xl">
                  Name
                </label>
                <input
                  id="name"
                  type="text"
                  name="name"
                  className="bg-white/15 outline-none placeholder:text-neutral-500 p-2 mt-2 rounded-md"
                  placeholder="Enter Product Name"
                />
              </div>

              <div className="flex flex-col">
                <label htmlFor="category" className="text-xl">
                  Category
                </label>
                <select
                  className="bg-white/15 outline-none placeholder:text-neutral-500 px-2 py-2.5 mt-2 rounded-md"
                  name="category"
                  id="category"
                >
                  <option className="text-neutral-800" value="">
                    Select Category
                  </option>
                  <option className="text-neutral-800" value="Electronics">
                    Electronics
                  </option>
                  <option className="text-neutral-800" value="Food">
                    Food
                  </option>
                  <option className="text-neutral-800" value="Vehicles">
                    Vehicles
                  </option>
                  <option className="text-neutral-800" value="Electrical">
                    Electrical
                  </option>
                  <option className="text-neutral-800" value="Household">
                    Household
                  </option>
                </select>
              </div>
            </div>

            <div className="">
              <button
                type="submit"
                className="bg-blue-600 hover:bg-blue-800 text-neutral-200 px-3 py-2 duration-200 rounded-sm"
              >
                Place Item
              </button>
            </div>
          </form>
        </div>

        {products?.length > 0 && (
          <div className="bg-white/5 flex flex-wrap justify-center items-center gap-5 border rounded-2xl border-neutral-600 h-[60vh] overflow-y-scroll no-scrollbar p-10 ">
            {products?.map((product: Products) => (
              <Link
                href={`/products/${product.id}`}
                key={product.id}
                className={`w-[200px] h-[200px] relative hover:scale-105 hover:shadow-lg shadow-cyan-500/50 hover:bg-neutral-500/10  border-2 border-neutral-500 p-4 duration-300 cursor-pointer rounded-sm flex flex-col justify-center items-center`}
              >
                <h2 className="text-xl font-bold text-center text-neutral-300">
                  {product.name}
                </h2>
                <p className="text-base text-neutral-500 ">{product.category}</p>
              </Link>
            ))}
          </div>
        )}

        {/* <div>
              <code>{"hello "}</code>
            </div>
         */}
      </div>
    </div>
  );
};

export default Products;
